version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:80"  # Maps the container's port 80 (Nginx) to the host's port 8080
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
